In [41]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

In [42]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")
homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")

E = np.eye(l[0])
print(O - E)


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.82113148 0.44225526 0.38884331]
 [0.457069   0.06606103 0.5552558 ]
 [0.71025141 0.41541112 0.07222707]]
Ділення:
 [[       inf 0.44225526 0.19442165]
 [       inf 0.06606103 0.2776279 ]
 [       inf 0.41541112 0.03611354]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[ True False False]
 [False False  True]
 [ True False False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
 

[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


C:\Users\Адмін\AppData\Local\Temp\ipykernel_15812\2890214979.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\Адмін\AppData\Local\Temp\ipykernel_15812\2890214979.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


In [43]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.mat(A)
MB = np.mat(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


In [44]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [45]:
D = np.ones(3)
Z = np.zeros((3,1))
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}")
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{np.concatenate((B, D))}
Для конкатенації з С
{C}
де С має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3,1)).shape}
в результаті ми можем виконати конкатенацію:
{np.concatenate((C, D.reshape((3,1))))}
При повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
{np.tile(D, (2, 3))}
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")



homework(f"""Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кількість рядкі та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім. Якщо розмірність масивів не спаівпадє використайте reshape.
Створіть декілька двовимірних масивів з сумарною розмірністю 12 та знайдіть всі можливі комбінції reshape. Наприклад, перша комбінація це рядок - {np.ones((1,12))}
""")

E = np.arange(1, 10).reshape(3, 3)
print(E, "\n\n", np.concatenate((E, E)), "\n\n", np.tile(E, 2),"\n")
F = np.arange(12).reshape(3,4)
print(F, "\n\n", np.concatenate((F.reshape(4,3), E)), "\n")
G = np.ones(12)
G1 = G.reshape(2,6)
G2 = G.reshape(3,4)
G3 = G.reshape(4,3)
G4 = G.reshape(6,2) 
G5 = G.reshape(12, 1)
print(G, "\n\n", G1, "\n\n", G2, "\n\n", G3, "\n\n", G4, "\n\n", G5)


При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]")
При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з В [1 2 3] розмірністю (3,):
[1. 2. 3. 1. 1. 1.]
Для конкатенації з С
[[1]
 [2]
 [3]]
де С має розмірність = (3, 1) потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
або
(3, 1)
в результаті ми можем виконати конкатенацію:
[[1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [1.]]
При повторенні D [1. 1. 1.] 2 рази для рядкі та 3 для стовпців будем мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]
Також можна перетворити двовимірний масив A розмірністю (3, 3) на рядок: [11 12 13 21 22 23 31 32 33] з розмірністю (9,)


>>>>> Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кіль

In [46]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

homework("""
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")

A = np.arange(12)
print(f"A - {A}, A.shape - {A.shape}, A.size - {A.size}, A.ndim - {A.ndim}")
A = A.reshape(3,4)
A_t = A.transpose()
A_fl = np.flip(A_t)
A_final = A_fl.reshape(12)
print(f"A.reshape - \n{A}\nA_t - \n{A_t}\nA_fl - \n{A_fl}\nA_final - {A_final}")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]


>>>>> 
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
 

A - [ 0  1  2  3  4  5  6  7  8  9 10 11], A.shape - (12,), A.size - 12, A.ndim - 1
A.reshape - 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A_t - 
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  